#!/bin/bash

set +avx

cd "`dirname "$0"`"
curl -D- --data-binary @Presentation.json -H "Content-Type: application/json" http://localhost:8083/presentations/new

cd Slides
for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14; do
	curl -D- -T Lezione.$((i+1)).png -H 'Content-Type: image/png' http://localhost:8083/presentations/at/1/slides/$i/image
done
